### PR TITLE
Fix up transaction stuff related to UploadHandler

### LINKED ISSUE #72: Fix transaction pattern in AptUploadHandler
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
It was discovered internally @sonatype that the way we handle Upload in UploadHandler is less than ideal in terms of how we open transactions.

* **What feature or behavior is this required for?**
Implementing a fix here will prevent a transaction from being opened and then later be invalidated due to either a security check or other issue.

* **How could we solve this issue? (Not knowing is okay!)**
https://github.com/sonatype-nexus-community/nexus-repository-apt/blob/master/src/main/java/net/staticsnow/nexus/repository/apt/AptUploadHandler.java#L75

Ideally ensurePermitted would occur before a Transaction is opened, and likely right after the TempBlob is created (as it looks like that's how you get your path)

* **Anything else?**
Let me know if you have any questions!

### PR DESCRIPTION
**Pull request by DarthHater**
Quick lil ditty to change when transactions occur, and hopefully simplify a bit of the code for AptUploadHandler

This pull request makes the following changes:
* new private method for doValidation (this could be useful if you allow uploading more than one file, as it seems right now only one is allowed?)
* Switch transaction stuff, use UnitOfWork.begin and UnitOfWork.end, move it to after we check security

It relates to the following issue #s:
* Fixes #72

### CODE REVIEW

**Comment by mpoindexter** [comment]
LGTM

File: src/main/java/net/staticsnow/nexus/repository/apt/AptUploadHandler.java [hunk 1]
```diff
@@ -61,26 +61,37 @@ public AptUploadHandler(@Named("simple") final VariableResolverAdapter variableR
...
+      String name = controlFile.getField("Package").map(f -> f.value).get();
+      String version = controlFile.getField("Version").map(f -> f.value).get();
+      String architecture = controlFile.getField("Architecture").map(f -> f.value).get();
+      String assetPath = FacetHelper.buildAssetPath(name, version, architecture);
+
+      doValidation(repository, assetPath);
+
+      UnitOfWork.begin(storageFacet.txSupplier());
+      try {
+        Asset asset = hostedFacet.ingestAsset(upload.getAssetUploads().get(0).getPayload());
```
Comment (j-s-3) [inline src/main/java/net/staticsnow/nexus/repository/apt/AptUploadHandler.java:79]: Is there already a transactional context here? As we no longer explicitly start the transaction, I was expecting an annotation on the method to do so for us.

**Comment by j-s-3** [comment]
Manual testing checks out.
